name = "MRIGradientCorrections"
uuid = "7cf23c51-5b1a-49d4-9594-91c6ec6e3098"
authors = ["Felix Horger <felix.horger@kcl.ac.uk>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
